# AcidIsland Configuration [version]
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
acid:
  # Acid can damage ops or not
  damage-op: true
  # Acid can damage chickens - best to leave false because they like to swim
  damage-chickens: false
  command:
    # Island Command. What command users will run to access their island
    island: ai
    # The island admin command.
    admin: acid
  damage:
    acid:
      # Damage that a player will experience in acid. 10 is half their health typically. 5 would be easier.
      player: 10
      # Damage that monsters experience from acid
      monster: 5
      # Damage animals experience from acid
      animal: 5
      # Destroy items after this many seconds in acid. 0 = do not destroy items
      item: 0
    # Damage from acid rain
    rain: 1
    # Portion effects from going into acid water
    # You can list multiple effects
    effects:
    - CONFUSION
    - BLINDNESS
    protection:
      # If player wears a helmet then they will not suffer from acid rain
      helmet: false
      # If player wears any set of full armor, they will not suffer from acid damage
      full-armor: false
world:
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: AcidIsland
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. AcidIsland_world, AcidIsland_world_nether, AcidIsland_world_end)
  world-name: AcidIsland_world
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: NORMAL
  # Radius of island in blocks. (So distance between islands is twice this)
  # Will be rounded up to the nearest 16 blocks.
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  distance-between-islands: 64
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /acid range set <player> <new range>
  # or set this permission: acidisland.island.range.<number>
  protection-range: 50
  # Start islands at these coordinates. This is where new islands will start in the
  # world. These must be a factor of your island distance, but the plugin will auto
  # calculate the closest location on the grid. Islands develop around this location
  # both positively and negatively in a square grid.
  # If none of this makes sense, leave it at 0,0.
  start-x: 0
  start-z: 0
  offset-x: 0
  offset-z: 0
  # Island height - Lowest is 5.
  # It is the y coordinate of the bedrock block in the schem.
  island-height: 50
  # Use your own world generator for this world.
  # In this case, the plugin will not generate anything.
  # /!\ This feature is experimental and might not work as expected or might not work at all.
  use-own-generator: false
  # Sea height (don't changes this mid-game unless you delete the world)
  # Minimum is 0, which means you are playing Skyblock!
  sea-height: 55
  # Maximum number of islands in the world. Set to -1 or 0 for unlimited. 
  # If the number of islands is greater than this number, no new island will be created.
  max-islands: 0
  # The default game mode for this world. Players will be set to this mode when they create
  # a new island for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # The default biome for the overworld
  default-biome: WARM_OCEAN
  # The maximum number of players a player can ban at any one time in this game mode.
  # The permission acidisland.ban.maxlimit.X where X is a number can also be used per player
  # -1 = unlimited
  ban-limit: -1
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    # Note: Some default challenges will not be possible if there is no nether.
    # Note that with a standard nether all players arrive at the same portal and entering a
    # portal will return them back to their islands.
    generate: true
    # Islands in Nether. Change to false for standard vanilla nether.
    islands: true
    # Sea height in Nether. Only operates if nether islands is true.
    # Changing mid-game will cause problems!
    sea-height: 55
    # Nether trees are made if a player grows a tree in the nether (gravel and glowstone)
    # Applies to both vanilla and islands Nether
    trees: true
    # Make the nether roof, if false, there is nothing up there
    # Change to false if lag is a problem from the generation
    # Only applies to islands Nether
    roof: true
    # Nether spawn protection radius - this is the distance around the nether spawn
    # that will be protected from player interaction (breaking blocks, pouring lava etc.)
    # Minimum is 0 (not recommended), maximum is 100. Default is 25.
    # Only applies to vanilla nether
    spawn-radius: 25
  end:
    # End Nether - if this is false, the end world will not be made and access to
    # the end will not occur. Other plugins may still enable portal usage.
    generate: true
    # Islands in The End. Change to false for standard vanilla end.
    islands: true
    # Sea height in The End. Only operates if end islands is true.
    # Changing mid-game will cause problems!
    sea-height: 55
    # /!\ This feature is experimental and might not work as expected or might not work at all.
    dragon-spawn: false
  # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
  # players return to their island if the island has been overrun by monsters.
  # This setting is toggled in world flags and set by the settings GUI.
  # Mob white list - these mobs will NOT be removed when logging in or doing /island
  remove-mobs-whitelist:
  - PIG_ZOMBIE
  - ENDERMAN
  - ZOMBIE_VILLAGER
  - WITHER
  # World flags. These are boolean settings for various flags for this world
  flags:
    CREEPER_DAMAGE: true
    PISTON_PUSH: false
    ISLAND_RESPAWN: true
    CREEPER_GRIEFING: false
    ENDERMAN_GRIEFING: true
    CLEAN_SUPER_FLAT: false
    CHEST_DAMAGE: false
    ENTER_EXIT_MESSAGES: true
    ENDERMAN_DEATH_DROP: true
    OFFLINE_REDSTONE: true
    REMOVE_MOBS: true
    ENDER_CHEST: false
    ITEM_FRAME_DAMAGE: false
  # These are the default protection settings for new islands.
  # The value is the minimum island rank required allowed to do the action
  # Ranks are: Visitor = 0, Member = 900, Owner = 1000
  default-island-flags:
    HURT_ANIMALS: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    ANVIL: 500
    FISH_SCOOPING: 500
    FIRE: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    TNT: 500
    FROST_WALKER: 500
    TURTLE_EGGS: 500
    COLLECT_LAVA: 500
    LEVER: 500
    RIDING: 500
    HURT_MONSTERS: 0
    ARMOR_STAND: 500
    NAME_TAG: 500
    TRADING: 0
    EGGS: 500
    ITEM_DROP: 0
    NOTE_BLOCK: 0
    NETHER_PORTAL: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 0
    BREWING: 500
    DROPPER: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 0
    PLACE_BLOCKS: 500
    ITEM_FRAME: 500
    CRAFTING: 0
    ENCHANTING: 0
    SHEARING: 500
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 0
    DISPENSER: 500
    GATE: 0
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    BREAK_BLOCKS: 500
    MOUNT_INVENTORY: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    JUKEBOX: 500
  # These are the default settings for new islands
  default-island-settings:
    PVP_END: false
    ANIMAL_SPAWN: true
    PVP_NETHER: false
    MONSTER_SPAWN: true
    FIRE_SPREAD: true
    PVP_OVERWORLD: false
  # These are the settings visible to users. (Not implemented yet)
  # /!\ This feature is experimental and might not work as expected or might not work at all.
  visible-settings: []
  # Visitor banned commands - Visitors to islands cannot use these commands in this world
  visitor-banned-commands:
  - spawner
  - spawnmob
island:
  # Default max team size
  # Use this permission to set for specific user groups: acidisland.team.maxsize.<number>
  # Permission size cannot be less than the default below.
  max-team-size: 4
  # Default maximum number of homes a player can have. Min = 1
  # Accessed via /ai sethome <number> or /ai go <number>
  # Use this permission to set for specific user groups: acidisland.island.maxhomes.<number>
  max-homes: 1
  name:
    # Island naming
    # Only players with the TODO can name their island
    # It is displayed in the top ten and enter and exit announcements
    # It replaces the owner's name. Players can use & for color coding if they have the TODO permission
    # These set the minimum and maximum size of a name.
    min-length: 4
    max-length: 20
  reset:
    # How many resets a player is allowed (override with /acid clearresets <player>)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 islands lifetime
    reset-limit: -1
    # Kicked or leaving players lose resets
    # Players who leave a team will lose an island reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # island by themselves and can only join a team.
    # Leave this true to avoid players exploiting free islands
    leavers-lose-reset: false
    # Allow kicked players to keep their inventory.
    # If false, kicked player's inventory will be thrown at the island leader if the
    # kicked player is online and in the island world.
    kicked-keep-inventory: false
    on-join:
      # What the plugin should reset when the player joins or creates an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
    on-leave:
      # What the plugin should reset when the player leaves or is kicked from an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
  require-confirmation:
    reset: true
    # Ask the player to confirm the command he is using by typing it again.
    # The 'wait' value is the number of seconds to wait for confirmation.
    kick: true
    kick-wait: 10
    leave: true
    leave-wait: 10
  # How long a player must wait before they can reset their island again in second
  reset-wait: 300
  make-island-if-none: false
  # Immediately teleport player to their island (home 1 if it exists) when entering the world
  immediate-teleport-on-island: false
  # Have player's respawn on their island if they die
  respawn-on-island: false
  sethome:
    nether:
      allow: true
      require-confirmation: true
    the-end:
      allow: true
      require-confirmation: true
  deaths:
    # Whether deaths are counted or not.
    counted: true
    # Maximum number of deaths to count. The death count can be used by add-ons.
    max: 10
    sum-team: false
    # When a player joins a team, reset their death count
    team-join-reset: true
  customranks: {}
protection:
  # Geo restrict mobs.
  # Mobs that exit the island space where they were spawned will be removed.
  geo-limit-settings: []
  # Invincible visitors. List of damages that will not affect visitors.
  # Make list blank if visitors should receive all damages
  invincible-visitors:
  - BLOCK_EXPLOSION
  - CONTACT
  - CUSTOM
  - DROWNING
  - ENTITY_ATTACK
  - ENTITY_EXPLOSION
  - FALL
  - FALLING_BLOCK
  - FIRE
  - FIRE_TICK
  - LAVA
  - LIGHTNING
  - MAGIC
  - POISON
  - PROJECTILE
  - STARVATION
  - SUFFOCATION
  - THORNS
  - WITHER
  - DRAGON_BREATH
  - FLY_INTO_WALL
  - HOT_FLOOR
  - CRAMMING
  - VOID
panel:
  # Whether GUIs should be closed when the player clicks outside.
  close-on-click-outside: true
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
uniqueId: config
